version: "3.9"
services:
  nginx:
    container_name: traffic_light_nginx
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/traffic_light/static/:ro
    ports:
      - "8080:80"
    depends_on:
      - django
    networks:
      - traffic_light

  django:
    container_name: backend
    build: ./core/
    restart: always
    env_file:
      - .env
    volumes:
      - .:/backend/
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/static/
    ports:
      - "8888:8888"
    depends_on:
      - redis
    networks:
      - traffic_light

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - traffic_light


volumes:
  uwsgi_data:
  web_static:

networks:
  traffic_light:
    driver: bridge
